/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminView;

import static java.awt.Color.WHITE;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author DISHA
 */
public class Teams extends javax.swing.JPanel {
    public static int count;
    
    /**
     * Creates new form Teams
     */
    public Teams() {
        initComponents();
        JPanel jpan;
        jpan = new JPanel();
        jpan.setBounds(0,0,1000,800);
        jpan.setBackground(WHITE);
        jpan.setOpaque(true);
        
        add(jpan);
        String query="SELECT COUNT(1) as NumberOfRows FROM `users`";
        Connection con=null;
        PreparedStatement st=null;
        try {
            
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/users_db","root","");
            st=con.prepareStatement(query);
            ResultSet rs=null;
            rs=st.executeQuery();
            rs.next();
            count=rs.getInt("NumberOfRows");
            con.close();
            st.close();
            rs.close();
            Connection con1=null;
            con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/users_db","root","");
            Statement st1=con1.createStatement();
            ResultSet rs1=null;
            rs1=st1.executeQuery("SELECT username FROM `users`");
            JLabel jLabels= new JLabel();
            jpan.removeAll();
            int j=1;
            while(rs1.next()){
                String data=rs1.getString(1);
                jLabels= new JLabel(j+". "+data);
                jLabels.setBorder(BorderFactory.createEmptyBorder(10,10,10,10));
                /*cb[j]= new JCheckBox("");
                /*JScrollPane jcrlp = new JScrollPane(cb);
                jcrlp.setPreferredSize(new Dimension(758,326));
                jpan.add(cb[j]);
                */
                jpan.add(jLabels);
                j++;
            }
            jpan.validate();
            jpan.repaint();
            
            con1.close();
            st1.close();
            rs1.close();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
