/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userview;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author DISHA
 */
public class Preference extends javax.swing.JPanel {
    String Username;
    int count;
    int[] TaskNumber = new int[500];
    String[] TaskName = new String[500];
    int[] Priority = new int[500];
    String[] StartDate = new String[500];
    /**
     * Creates new form Preference
     */
    public Preference(String UserName) {
        Username=UserName;
        initComponents();
        jLabel1.setText("<html>Perference according to priority</html>");
        String query="SELECT `id` FROM `users` where users.username='"+UserName+"'";
        Connection con,con1,con2=null;
        PreparedStatement st,st1,st2=null;
        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/users_db","root","");
            st=con.prepareStatement(query);
            ResultSet rs=null;
            rs=st.executeQuery();
            rs.next();
            int id=rs.getInt("id");
            String query1="SELECT COUNT(*) AS ROWCOUNT FROM `addpeople` WHERE lid="+id;
            con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/users_db","root","");
            st1=con1.prepareStatement(query1);
            ResultSet rs1=null;
            rs1=st1.executeQuery();
            rs1.next();
            count = rs1.getInt("ROWCOUNT");
            String query2="SELECT `Task number` FROM `addpeople` WHERE lid="+id;
            con2=DriverManager.getConnection("jdbc:mysql://localhost:3306/users_db","root","");
            st2=con2.prepareStatement(query2);
            ResultSet rs2=null;
            rs2=st2.executeQuery();
            int i=0;
            while(rs2.next()){
            TaskNumber[i] = rs2.getInt("Task number");
            i++;
            }
            rs2.close();
            Connection con3=null;
            PreparedStatement st3=null;
            con3=DriverManager.getConnection("jdbc:mysql://localhost:3306/users_db","root","");
            for(int j=0;j<count;j++){
                int tasknumber=TaskNumber[j];
                String query3="SELECT `TaskName`, `StartDate`, `Priority` FROM `properties2` WHERE `Task number`="+tasknumber;
                st3=con3.prepareStatement(query3);
                ResultSet rs3=null;
                rs3=st3.executeQuery();
                rs3.next();
                TaskName[j] = rs3.getString("TaskName");
                StartDate[j] = rs3.getString("StartDate");
                Priority[j] = rs3.getInt("Priority");
            }
            } catch (SQLException ex) {
            Logger.getLogger(MainCopy.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        priority();
        JPanel jpan;
        jpan = new JPanel();
        jpan.setBounds(100,100,758,326);
        jpan.setOpaque(true);
        add(jpan);
        JLabel jLabels= new JLabel();
        jpan.removeAll();
        for(int j=0;j<count;j++){
                jLabels= new JLabel(j+1+".  "+TaskName[j]);
                jLabels.setBorder(BorderFactory.createEmptyBorder(10,10,10,10));
                /*cb[j].setBounds(150,150,50,50);
                JScrollPane jcrlp = new JScrollPane(cb);
                cb[j].setPreferredSize(new Dimension(758,326));*/
                jpan.add(jLabels);
        }
        jpan.validate();
        jpan.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(385, 385, 385)
                .addComponent(jLabel1)
                .addContainerGap(386, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(325, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

        void priority(){
        for(int i=0;i<count-1;i++)
        {
            for(int j=i+1;j<count;j++)
            {
                if(Priority[i]<Priority[j])
                {
                int x=Priority[i];
                Priority[i]=Priority[j];
                Priority[j]=x;
                String y=StartDate[i];
                StartDate[i]=StartDate[j];
                StartDate[j]=y;
                String z=TaskName[i];
                TaskName[i]=TaskName[j];
                TaskName[j]=z;
                }/*
                else if(Priority[i]==Priority[j]){
                    if(StartDate[i].compareTo(StartDate[j])<0){
                        int x=Priority[i];
                        Priority[i]=Priority[j];
                        Priority[j]=x;
                        String y=StartDate[i];
                        StartDate[i]=StartDate[j];
                        StartDate[j]=y;
                        String z=TaskName[i];
                        TaskName[i]=TaskName[j];
                        TaskName[j]=z;
                        }
                    else{
                        int x=Priority[j];
                        Priority[j]=Priority[i];
                        Priority[i]=x;
                        String y=StartDate[j];
                        StartDate[j]=StartDate[i];
                        StartDate[i]=y;
                        String z=TaskName[j];
                        TaskName[j]=TaskName[i];
                        TaskName[i]=z;
                    }
                }*/
            }
        }
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
        }
